name: roxum
description: "A minimal and powerful IDE for Android."
publish_to: 'none'
version: 2.3.2+38

environment:
  sdk: ^3.12.2

dependencies:
  android_intent_plus: ^6.0.0
  bloc: ^9.2.1
  code_forge: ^10.7.0
  cryptography: ^2.9.0
  dartssh2: ^2.22.5
  diff_match_patch: ^0.4.1
  equatable: ^2.1.0
  file_picker: ^11.0.3
  flutter:
    sdk: flutter
  flutter_archive: ^6.3.1
  flutter_bloc: ^9.1.1
  flutter_colorpicker: ^1.1.0
  flutter_file_downloader: ^2.1.1
  flutter_inappwebview: ^6.1.5
  flutter_json: ^0.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_pdfview: ^1.4.4
  flutter_pty: ^0.4.1
  flutter_secure_storage: ^10.3.1
  flutter_svg: ^2.3.0
  flutter_web_auth_2: ^5.0.3
  font_awesome_flutter: ^11.0.0
  html: ^0.15.6
  http: ^1.2.2
  llama_flutter_android: { git: https://github.com/heckmon/Llama-Flutter.git }
  markdown: ^7.3.1
  markdown_widget: ^2.3.2+8
  meta: ^1.17.0
  path: ^1.9.0
  percent_indicator: ^4.2.5
  re_highlight: ^0.0.3
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  vector_math: ^2.2.0
  xterm: ^4.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/material_icons/
    - assets/webview/
    - assets/fonts/
    - assets/certificates/
  fonts:
    - family: firaCode
      fonts:
        - asset: assets/fonts/FiraCode-Medium.ttf
    - family: cascadia
      fonts:
        - asset: assets/fonts/CascadiaCodePL-Regular.ttf
    - family: hack
      fonts:
        - asset: assets/fonts/Hack-Regular.ttf
    - family: dejaVuSansMono
      fonts:
        - asset: assets/fonts/DejaVuSansMono.ttf
    - family: inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
    - family: jetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
    - family: proggy
      fonts:
        - asset: assets/fonts/ProggyVector-Regular.ttf
    - family: sourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-Medium.ttf
    