import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_svg/svg.dart';
import 'package:roxum/l10n/app_localizations.dart';

import '../bloc/ui_bloc/ui_bloc.dart';
import '../terminal/terminal.dart';
import '../utils/constants.dart';

sealed class ProjectTemplates {
  final String title, subtitle;
  final dynamic icon;
  final BuildContext context;

  const ProjectTemplates({
    required this.context,
    required this.title,
    required this.subtitle,
    required this.icon
  });
}

class PlainTemplates extends ProjectTemplates {
  final Map<String, String> fileNameAndContent;

  const PlainTemplates({
    required super.context,
    required super.title,
    required super.subtitle,
    required super.icon,
    required this.fileNameAndContent
  });

  Future<void> generateContent(String projectName) async{
    final dir = Directory("$projectDir/$projectName");

    if (await dir.exists() && !(await dir.list().isEmpty)) {
      if (!context.mounted) return;

      final appTheme = context.read<AppThemeBloc>().state.appTheme;
      final shouldOverwrite = await showDialog<bool>(
        context: context,
        builder: (ctx) => AlertDialog(
          backgroundColor: appTheme.isDark
              ? const Color(0xff2b2b2b)
              : const Color.fromARGB(255, 240, 240, 240),
          title: Text(
            'Project already exists',
            style: TextStyle(color: appTheme.selectScreenCardTextColor),
          ),
          content: Text(
            'A project with this name already exists. Do you want to overwrite it?',
            style: TextStyle(color: appTheme.selectScreenCardTextColor.withAlpha(200)),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.of(ctx).pop(false),
              style: TextButton.styleFrom(
                foregroundColor: appTheme.selectScreenCardTextColor
              ),
              child: const Text('Cancel'),
            ),
            ElevatedButton(
              onPressed: () => Navigator.of(ctx).pop(true),
              style: ElevatedButton.styleFrom(
                foregroundColor: Colors.white,
                backgroundColor: Colors.redAccent
              ),
              child: const Text('Overwrite'),
            ),
          ],
        ),
      );

      if (shouldOverwrite != true) {
        return;
      }
    } else {
      dir.createSync(recursive: true);
    }

    for(final fileItem in fileNameAndContent.entries){
      final file = File("${dir.path}/${fileItem.key}");
      if(!(await file.exists())){
        await file.create();
      }

      if(await file.exists() && (await file.readAsString()).isEmpty) {
        await file.writeAsString(fileItem.value);
      }
    }
  }
}

class CLITemplates extends ProjectTemplates {
  final String command;
  final bool isVite;
  final bool appendProjectName;
  final bool openAfterCreate;
  final List<TemplateRequirement> requirements;

  String _command;

  CLITemplates({
    required super.context,
    required super.title,
    required super.subtitle,
    required super.icon,
    required this.command,
    this.isVite = false,
    this.appendProjectName = false,
    this.openAfterCreate = false,
    this.requirements = const [],
  }) : _command = command ;

  String _shellEscape(String value) {
    if (value.isEmpty) return "''";
    final safeChar = RegExp(r'[A-Za-z0-9_./:-]');
    final isSafe = value.runes.every(
      (rune) => safeChar.hasMatch(String.fromCharCode(rune)),
    );
    if (isSafe) {
      return value;
    }
    return "'${value.replaceAll("'", "'\\''")}'";
  }

  set name(String n) {
    final trimmed = n.trim();
    if (!appendProjectName || trimmed.isEmpty) {
      _command = command;
      return;
    }
    _command = '$command ${_shellEscape(trimmed)}';
  }

  EmbeddedTerminal runCommand(){
    final commandToRun = 'cd ${_shellEscape(projectDir)} && $_command';
    return EmbeddedTerminal(
      projectDir: projectDir,
      args: ["-c", commandToRun],
    );
  }
}

class TemplateRequirement {
  final String binaryPath;
  final String title;

  const TemplateRequirement({
    required this.binaryPath,
    required this.title,
  });
}


List<ProjectTemplates> projTemps(BuildContext context) {
  final l10n = AppLocalizations.of(context)!;
  return [
  PlainTemplates(
    context: context,
    title: l10n.webTemplateTitle,
    subtitle: l10n.webTemplateSubtitle,
    icon: SvgPicture.asset("assets/material_icons/web.svg", width: 30, height: 30),
    fileNameAndContent: {
      "index.html": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>My Web Project</title>\n    <link rel=\"stylesheet\" href=\"style.css\">\n  </head>\n  <body>\n    <header>\n      <h1>Welcome to My Web Project</h1>\n      <p>This is a starter template generated by Roxum.</p>\n    </header>\n    <main>\n      <button id=\"countBtn\">Click me</button>\n      <p id=\"count\">Clicked 0 times</p>\n    </main>\n    <script src=\"script.js\"></script>\n  </body>\n</html>\n",
      "style.css": "/* Basic styling for the starter template */\nhtml, body {\n  height: 100%;\n  margin: 0;\n  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;\n  background: linear-gradient(135deg, #4f46e5 0%, #38bdf8 100%);\n  color: #111827;\n}\n\nbody {\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  padding: 2rem;\n}\n\nheader {\n  text-align: center;\n  background: rgba(255, 255, 255, 0.85);\n  border-radius: 1rem;\n  padding: 2rem;\n  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15);\n}\n\nbutton {\n  appearance: none;\n  border: none;\n  padding: 0.75rem 1.5rem;\n  border-radius: 999px;\n  background: #2563eb;\n  color: white;\n  font-weight: 600;\n  cursor: pointer;\n  transition: transform 0.2s ease, box-shadow 0.2s ease;\n}\n\nbutton:hover {\n  transform: translateY(-1px);\n  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);\n}\n\nbutton:active {\n  transform: translateY(0);\n  box-shadow: none;\n}\n",
      "script.js": "// Simple script to demonstrate interactivity\nconst button = document.getElementById(\"countBtn\");\nconst countEl = document.getElementById(\"count\");\nlet count = 0;\n\nif (button && countEl) {\n  button.addEventListener(\"click\", () => {\n    count += 1;\n    countEl.textContent = `Clicked \${count} time\${count === 1 ? \"\" : \"s\"}`;\n  });\n}\n"
    }
  ),

  CLITemplates(
    context: context,
    title: l10n.viteAppTemplateTitle,
    subtitle: l10n.viteAppTemplateSubtitle,
    isVite: true,
    appendProjectName: true,
    openAfterCreate: true,
    icon: SvgPicture.asset("assets/material_icons/vitejs.svg", width: 30, height: 30),
    command: "npm init -y && npm install -g create-vite@latest && node /data/data/com.roxum/runtimes/node/lib/node_modules/create-vite/dist/index.js"
  ),

  CLITemplates(
    context: context,
    title: l10n.dartAppTemplateTitle,
    subtitle: l10n.dartAppTemplateSubtitle,
    appendProjectName: true,
    openAfterCreate: true,
    requirements: [
      TemplateRequirement(
        binaryPath: '$binDir/dart',
        title: l10n.dartRuntime,
      ),
    ],
    icon: SvgPicture.asset("assets/material_icons/dart.svg", width: 30, height: 30),
    command: "dart create"
  ),

  CLITemplates(
    context: context,
    title: l10n.rustAppTemplateTitle,
    subtitle: l10n.rustAppTemplateSubtitle,
    appendProjectName: true,
    openAfterCreate: true,
    requirements: [
      TemplateRequirement(
        binaryPath: '$binDir/cargo',
        title: l10n.rustRuntime,
      ),
    ],
    icon: SvgPicture.asset("assets/material_icons/rust.svg", width: 30, height: 30),
    command: "cargo new"
  ),
  ];
}